// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6e9cjW-TLouOpghjp5eoCPVsSwx1cWas',
    appId: '1:180204251130:web:40ae9cb1f1338a0e572643',
    messagingSenderId: '180204251130',
    projectId: 'employee-attendance-30f81',
    authDomain: 'employee-attendance-30f81.firebaseapp.com',
    storageBucket: 'employee-attendance-30f81.appspot.com',
    measurementId: 'G-1MSTLWM8FY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADeZIMYS13dfJLQimh47WJX0VU5jJ6ZkE',
    appId: '1:180204251130:android:71dbf5be46274975572643',
    messagingSenderId: '180204251130',
    projectId: 'employee-attendance-30f81',
    storageBucket: 'employee-attendance-30f81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOE7yizrPu-bJuzfaDrGEsttuISnWOrak',
    appId: '1:180204251130:ios:44926ea0f127c595572643',
    messagingSenderId: '180204251130',
    projectId: 'employee-attendance-30f81',
    storageBucket: 'employee-attendance-30f81.appspot.com',
    iosBundleId: 'com.royalcourtbd.employeeAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOE7yizrPu-bJuzfaDrGEsttuISnWOrak',
    appId: '1:180204251130:ios:44926ea0f127c595572643',
    messagingSenderId: '180204251130',
    projectId: 'employee-attendance-30f81',
    storageBucket: 'employee-attendance-30f81.appspot.com',
    iosBundleId: 'com.royalcourtbd.employeeAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6e9cjW-TLouOpghjp5eoCPVsSwx1cWas',
    appId: '1:180204251130:web:56b46143b8914ba8572643',
    messagingSenderId: '180204251130',
    projectId: 'employee-attendance-30f81',
    authDomain: 'employee-attendance-30f81.firebaseapp.com',
    storageBucket: 'employee-attendance-30f81.appspot.com',
    measurementId: 'G-KC6LJV485V',
  );
}
